### ISSUE TITLE
ブロックの追加

### ISSUE THREAD

**Issue by KeijiInformation** [a2110027/J1-8#12]
・壊せないブロック
・下方向にすり抜け可能なブロック
・棘ブロック

**Comment by a2110027** [comment]
壊せないブロックは、既に実装済み。
下方向にすり抜け可能なブロック及び針ブロックを追加実装(仮のグラフィック有)  
当たり判定の実装をお願いします。

**Comment by a2110027** [comment]
右向きの針　id = 4
左向きの針　id = 5
落下する針　id = 6
グラフィックも含めて実装しました。
当たり判定や落下判定お願いします！

**Comment by a2110027** [comment]
落下は無理そう。やっときました。
